export const NAVIGATION_LINKS = {
  HOME: "/",
  QUIENES_SOMOS: "/quienes-somos",
  SERVICIOS: "/servicios",
  CONTACTO: "/contacto",
  BLOG: "/blog",
  YACHT_BROKER: "/yacht-broker",
  YACHT_CHARTER: "/yacht-charter",
  INSPECCIONES: "/inspections",
  LOGÍSTICA: "/logistics",
  ASESORIA_NAUTICA: "nautical-consulting",
  BUNKER_SUPPLY: "bunker-supply",
  VALOR_AÑADIDO: "added-value-services",
  PROVEEDORES_Y_DISTRIBUIDORES: "/proveedores-y-distribuidores",
  DIARIO_PUERTO_MAHON: "/diario",
  CONDICIONES_Y_TARIFAS: "/condiciones-y-tarifas",
  CONTRATOS_DE_COMPRAVENTA: "/contratos-de-compraventa",
  POLITICA_DE_PRIVACIDAD: "/politica-de-privacidad",
  AVISO_LEGAL: "/aviso-legal",

  PUBLIC_INSTANT_RATE: "/my-rate?instantRate=true",
  ENVIO_BY_ID: (id: string) => `/app/orders/${id}`,
  ENVIO_NEW: (rateId: string) => `/app/rates?orderRateId=${rateId}`,
  ENVIO_EDIT: (orderId: string) => `/app/orders/${orderId}/edit`,
  RATE_EDIT: (id: string) => `/app/rates/${id}/edit`,
  RATE_BY_ID: (rateId: string) => `/app/rates?rateId=${rateId}`,
  ADDRESSES: "/app/addresses",
  HOLDED_INVOICE: (id: string) =>
    `${process.env.NEXT_PUBLIC_HOLDED_INVOICE + id}`,
  API_LANDING: "/api-landing",
  PUBLIC_TRACKING: (id: string) =>
    process.env.NEXT_PUBLIC_APP_URL + `/tracking/${id}`,
};
