export const NAVIGATION_LINKS = {
  HOME: "/",
  QUIENES_SOMOS: "/quienes-somos",
  SERVICIOS: "/servicios",
  CONTACTO: "/contacto",
  BLOG: "/blog",
  PROFILE_PLANS: "app/profile?tab=api",
  YACHT_BROKER: "/yacht-broker",
  YACHT_CHARTER: "/yacht-charter",
  INSPECCIONES: "/inspections",
  LOGÍSTICA: "/logistics",
  ASESORIA_NAUTICA: "nautical-consulting",
  SHIP_BROKER: "ship-broker",
  VALOR_AÑADIDO: "added-value-services",
  BLOG_CATEGORY: (slug: string) => `/blog/category/${slug}`,
  AREA_CLIENTE: "/app",
  SEGUROS_TRANSPORTES: "/legal#seguros-transportes",
  LEGAL: "/legal",
  CONDICIONES_CONTRATACION: "/legal#condiciones-contratacion",
  PROTECCION_DATOS: "/legal#proteccion-datos",
  LOGIN: "/auth/login",
  RESET_PASSWORD: "/auth/reset-password",
  REGISTER: "/auth/register",
  ANALYTICS: "/app/analytics",
  MI_PERFIL: "/app/profile",
  ENVIOS: "/app/orders",
  MIS_COTIZACIONES: "/app/rates",
  INSTANT_RATE: "/app/rates?instantRate=true",
  PUBLIC_INSTANT_RATE: "/my-rate?instantRate=true",
  ENVIO_BY_ID: (id: string) => `/app/orders/${id}`,
  ENVIO_NEW: (rateId: string) => `/app/rates?orderRateId=${rateId}`,
  ENVIO_EDIT: (orderId: string) => `/app/orders/${orderId}/edit`,
  RATE_EDIT: (id: string) => `/app/rates/${id}/edit`,
  RATE_BY_ID: (rateId: string) => `/app/rates?rateId=${rateId}`,
  ADDRESSES: "/app/addresses",
  HOLDED_INVOICE: (id: string) =>
    `${process.env.NEXT_PUBLIC_HOLDED_INVOICE + id}`,
  API_LANDING: "/api-landing",
  PUBLIC_TRACKING: (id: string) =>
    process.env.NEXT_PUBLIC_APP_URL + `/tracking/${id}`,
};
